### ISSUE TITLE
Show time/alloc both as a % of the root node, and overall

### ISSUE THREAD

**Issue by ndmitchell** [jaspervdj/profiteur#10]
When you zoom in all the inards have their time/alloc reported as a % of the zoom root. It would be good to have both relative to that, and also relative to MAIN, so I can see a computation is 80% of this subtree, but only 1% overall.

**Comment by jaspervdj** [comment]
@ndmitchell Thanks for suggesting all these improvements.  The fixes are in `profiteur-0.4.0.0`.

**Comment by ndmitchell** [comment]
And thanks for your work on it, I'm very impressed.
