### ISSUE TITLE
Move the function name beneath the zoom/parent buttons

### ISSUE THREAD

**Issue by ndmitchell** [jaspervdj/profiteur#15]
At the moment when clicking around there is a lot of changing text below the zoom/parent buttons, and just the function name above, which requires my eyes to keep scanning above/below to see the effect. I think it would be a minor UI improvement to have the function name below - just above module.

**Comment by jaspervdj** [comment]
This change and #14, #13 have been released as `profiteur-0.4.1.0`.

**Comment by ndmitchell** [comment]
Thanks!
