### ISSUE TITLE
Broken with GHC 8.0.2

### ISSUE THREAD

**Issue by ndmitchell** [jaspervdj/profiteur#16]
The `.prof` output style with GHC 8.0.2 seems to have changed, with a slightly different summary table at the top, including file locations. That seems to have broken profiteur.

**Comment by ndmitchell** [comment]
Note that @maoe diagnosed and fixed this as part of https://github.com/maoe/ghc-prof/issues/4, which should give a clue as to what the fix is. A possible alternative direction would be to use `ghc-prof` directly, freeing you from parsing the `.prof` file yourself.

**Comment by jaspervdj** [comment]
I've just uploaded `profiteur-0.4.2.0`, which fixes the issue by switching to `ghc-prof`.

Thanks for that package @maoe, it works great!
