### ISSUE TITLE
Failed reading: takeWhile1

### ISSUE THREAD

**Issue by flip111** [jaspervdj/profiteur#17]
compile: `stack build --profile --ghc-options="-j4 -auto-all -rtsopts"`
run: `stack exec -- bowtie --help +RTS -p`

prof file (paste stays available until 1 september 2017) https://fnpaste.com/N9Z3

**Comment by jaspervdj** [comment]
Which version of `profiteur` are you using?  Could you try with the latest one, `0.4.2.2`?

**Comment by flip111** [comment]
lts-6.30
do you recommend cloning repo or upgrade global-project ?

**Comment by flip111** [comment]
I cloned the repo and build it, now i don't get this error anymore.
