### ISSUE TITLE
Normalize metrics to zoomed scope

### ISSUE THREAD

**Issue by tobbebex** [jaspervdj/profiteur#5]
Hi, 

First off, I LOVE profiteur, profiling large applications without it would be impossible. So THANK you for providing this!

I have a use case where I am optimizing the runtime of a 3D game, where loading the level takes considerable amount of time, and its share is dependent on how long you play after loading. To not be skewed by this, I use the "zoom" functionality of profiteur to zoom in on the runtime rendering part. 

Using this, I have been able to optimize one hot spot to become smaller in proportion to this scope, by just looking at the area of the colored square. BUT, when I look at the metrics (Inherited time, Inherited alloc) the numbers doesn't make sense since its not scaled to the zoomed scope, and are still skewed by how long I was playing in relation to level loading.

Could it be possible to normalize all numbers to the zoomed scope? Right after clicking zoom, the new top level should show 100% in inherited time and alloc.

**Comment by jaspervdj** [comment]
Hey, I've made this change on the master branch. However, I haven't been able to test it out extensively. Could you let me know if the git version works for you?

**Comment by tobbebex** [comment]
Hi, wow that's fast! :)

The inherited metrics seems to work correctly, though the individual ones are scaled wrong. Right after clicking zoom, the inherited time and alloc goes to 100 as expected, but so do the individual ones! They should really be scaled using the same divisor as the inherited time and alloc, and only ever be 100 for a scope with no children.

**Comment by tobbebex** [comment]
On that note BTW, even in the old version, selecting a (indiv) node and its parent yielded the same metrics. To be consistent, I think the (indiv) node should show the individual metrics values for the inherited ones (since an (indiv) doesn't have any children).

**Comment by jaspervdj** [comment]
Oh, of course, stupid of me. I'll fix it tomorrow.

**Comment by jaspervdj** [comment]
I fixed the first issue.

Regarding your other comment, I think you are right as well. In fact, I think it would be better to restructure the tree so that there are only two types of nodes: parents (with only inherited time/alloc), and leafs (with only individual time/alloc). I can do this restructuring on the Haskell side, and the JS doesn't have to care too much about it.

**Comment by jaspervdj** [comment]
@tobbebex I've done a bit of a refactor, so that the individual nodes are now shown separately, as leafs, or merged when appropriate. I would be interested in how well it works for your 3D game. I think it is nicer for the few large Haskell applications I've tried it on.

**Comment by tobbebex** [comment]
Looks good! I noticed that the (indiv) tags doesn't share color with their parents anymore, but with this rewrite it matters less than before. Good job!
