### ISSUE TITLE
Output should include an HTML link to the help page

### ISSUE THREAD

**Issue by ndmitchell** [jaspervdj/profiteur#9]
Both for convenience, and for branding.

**Comment by jaspervdj** [comment]
A link is already shown if you press the "help" button.  I would prefer not to take up too much screen real estate.

**Comment by ndmitchell** [comment]
Your choice in the end, however, there's nothing to immediately say the profile was created with profiteur, and the link in the help button is not clickable. Fixing the non-clickable link would still be nice.
